name: Build CI

on:
    push:
    pull_request:
    release:
        types: [published]
    check_suite:
        types: [rerequested]

jobs:
    test:
        runs-on: ubuntu-18.04
        container: debian:buster

        steps:
            - name: install dependencies
              run: |
                apt-get update
                apt-get --no-install-recommends -y install build-essential cbmc asciidoc asciidoc-dblatex source-highlight fop python3 git
            - name: checkout
              uses: actions/checkout@v2
            - name: build
              run: |
                make -O V=1 -j$(nproc)
            - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              name: publish
              run: |
                git config user.email "jepler@gmail.com"
                git config user.name "Jeff Epler (github actions)"
                git remote set-url --push origin https://jepler:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                make -O V=1 publish
